version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:40"
      timezone: America/Toronto
    open-pull-requests-limit: 5
    groups:
      routine-updates:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]
      security-updates:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:40"
      timezone: America/Toronto
    open-pull-requests-limit: 5
    groups:
      routine-updates:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]
      security-updates:
        applies-to: security-updates
        patterns: ["*"]
