permissions:
  contents: read
  pull-requests: write

name: License Check

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  license_check:
    uses: OpenVoiceOS/gh-automations/.github/workflows/license-check.yml@e1770fb608f8c39ab886ff336f6470ee17747b0d # dev
    with:
      pr_comment: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
